In [2]:
# dataframe的创建方式
import pandas as pd
import numpy as np
from streamlit import columns

# 通过series来创建
s1=pd.Series([1,2,3,4,5])
s2=pd.Series([6,7,8,9,10])
df=pd.DataFrame({"第1列":s1,"第2列":s2})
df

   第1列  第2列
0    1    6
1    2    7
2    3    8
3    4    9
4    5   10

In [4]:
# 通过字典来创建
df=pd.DataFrame(
    {
    "name":['tom','jack','alice','bob','allen'],
    "age":[15,17,20,26,30],
    "score":[60.5,80,30.6,70,100]
    },index=[1,2,3,4,5],columns=["name","score","age"]
)
df

    name  score  age
1    tom   60.5   15
2   jack   80.0   17
3  alice   30.6   20
4    bob   70.0   26
5  allen  100.0   30

In [6]:
# dataframe的属性
print(df.index)
print(df.columns)
print(df.values)

Index([1, 2, 3, 4, 5], dtype='int64')
Index(['name', 'score', 'age'], dtype='object')
[['tom' 60.5 15]
 ['jack' 80.0 17]
 ['alice' 30.6 20]
 ['bob' 70.0 26]
 ['allen' 100.0 30]]

In [8]:
print(df.ndim)
print(df.shape)
print(df.size)
print(df.dtypes)
df

2
(5, 3)
15
name      object
score    float64
age        int64
dtype: object

    name  score  age
1    tom   60.5   15
2   jack   80.0   17
3  alice   30.6   20
4    bob   70.0   26
5  allen  100.0   30

In [10]:
print(df.T)

          1     2      3     4      5
name    tom  jack  alice   bob  allen
score  60.5  80.0   30.6  70.0  100.0
age      15    17     20    26     30

In [11]:
print(df.loc[4])
print(df.iloc[3])

name      bob
score    70.0
age        26
Name: 4, dtype: object
name      bob
score    70.0
age        26
Name: 4, dtype: object

In [15]:
print(df.loc[:,'name'])
print(df.iloc[:,0])
print(df)

1      tom
2     jack
3    alice
4      bob
5    allen
Name: name, dtype: object
1      tom
2     jack
3    alice
4      bob
5    allen
Name: name, dtype: object
    name  score  age
1    tom   60.5   15
2   jack   80.0   17
3  alice   30.6   20
4    bob   70.0   26
5  allen  100.0   30

In [18]:
print(df.at[3,'score'])
print(df.iat[2,1])
print(df.loc[3,'score'])
print(df.loc[3,'score'])
print(df.iloc[2,1])

30.6
30.6
30.6
30.6
30.6

In [26]:
print(df['name'])
print(type(df['name']))
print(df.name)
print(type(df.name))
print(df[['name']])
print(type(df[['name']]))
df[['name']]

1      tom
2     jack
3    alice
4      bob
5    allen
Name: name, dtype: object
<class 'pandas.core.series.Series'>
1      tom
2     jack
3    alice
4      bob
5    allen
Name: name, dtype: object
<class 'pandas.core.series.Series'>
    name
1    tom
2   jack
3  alice
4    bob
5  allen
<class 'pandas.core.frame.DataFrame'>

    name
1    tom
2   jack
3  alice
4    bob
5  allen

In [27]:
print(df[['name','score']])

    name  score
1    tom   60.5
2   jack   80.0
3  alice   30.6
4    bob   70.0
5  allen  100.0

In [28]:
print(df.head(3))

    name  score  age
1    tom   60.5   15
2   jack   80.0   17
3  alice   30.6   20

In [29]:
print(df.tail(2))

    name  score  age
4    bob   70.0   26
5  allen  100.0   30

In [32]:
df[df.score>70]

    name  score  age
2   jack   80.0   17
5  allen  100.0   30

In [33]:
df[(df['score']>70)&(df.age>20)]

    name  score  age
5  allen  100.0   30

In [34]:
df.sample(3)

    name  score  age
3  alice   30.6   20
2   jack   80.0   17
4    bob   70.0   26

In [35]:
df = pd.DataFrame(
    {
        "name":["tom",'jack','alice','bob','allen'],
        "age":[15,17,20,26,30],
        "score":[60.5,80,30.6,70,83.5]
    },index=[1,2,3,4,5],columns=["name","score","age"]
)

In [36]:
print(df.head()) #查看前n行数据，默认是5行
print(df.tail(1))  #查看后n行数据，默认是5行

    name  score  age
1    tom   60.5   15
2   jack   80.0   17
3  alice   30.6   20
4    bob   70.0   26
5  allen   83.5   30
    name  score  age
5  allen   83.5   30

In [37]:
print(df.isin(['jack',20]))  #查看元素是否包含在参数集合中

    name  score    age
1  False  False  False
2   True  False  False
3  False  False   True
4  False  False  False
5  False  False  False

In [39]:
print(df.isna())

    name  score    age
1  False  False  False
2  False  False  False
3  False  False  False
4  False  False  False
5  False  False  False

In [44]:
print(df['score'].sum())
print(df.score.max())
print(df.age.min())
print(df.score.mean())
print(df.score.median())
print(df.age.mode())
print(df)

324.6
83.5
15
64.92
70.0
0    15
1    17
2    20
3    26
4    30
Name: age, dtype: int64
    name  score  age
1    tom   60.5   15
2   jack   80.0   17
3  alice   30.6   20
4    bob   70.0   26
5  allen   83.5   30

In [45]:
print(df.age.mode())

0    15
1    17
2    20
3    26
4    30
Name: age, dtype: int64

In [ ]:
df = pd.DataFrame(
    {
        "name":["tom","tom",'jack','alice','bob','allen'],
        "age":[15,15,15,20,26,30],
        "score":[60.5,60.5,80,30.6,70,83.5]
    },index=[1,2,3,4,5,6],columns=["name","score","age"]
)

In [46]:
print(df.score.std())
print(df.score.var())
print(df.score.quantile(0.25))

21.188605428390044
448.957
60.5

In [47]:
print(df.describe())

           score        age
count   5.000000   5.000000
mean   64.920000  21.600000
std    21.188605   6.268971
min    30.600000  15.000000
25%    60.500000  17.000000
50%    70.000000  20.000000
75%    80.000000  26.000000
max    83.500000  30.000000

In [48]:
print(df.count())

name     5
score    5
age      5
dtype: int64

In [49]:
print(df.value_counts())

name   score  age
alice  30.6   20     1
allen  83.5   30     1
bob    70.0   26     1
jack   80.0   17     1
tom    60.5   15     1
Name: count, dtype: int64

In [50]:
print(df.drop_duplicates())

    name  score  age
1    tom   60.5   15
2   jack   80.0   17
3  alice   30.6   20
4    bob   70.0   26
5  allen   83.5   30

In [51]:
print(df.duplicated(subset=['age']))

1    False
2    False
3    False
4    False
5    False
dtype: bool

In [53]:
df.sample(2)

    name  score  age
3  alice   30.6   20
1    tom   60.5   15

In [54]:
print(df.replace(15,20))

    name  score  age
1    tom   60.5   20
2   jack   80.0   17
3  alice   30.6   20
4    bob   70.0   26
5  allen   83.5   30

In [56]:
df.cumsum()
df.cummin(axis=0)

    name  score  age
1    tom   60.5   15
2   jack   60.5   15
3  alice   30.6   15
4  alice   30.6   15
5  alice   30.6   15

In [58]:
print(df.sort_index(ascending=False))

    name  score  age
5  allen   83.5   30
4    bob   70.0   26
3  alice   30.6   20
2   jack   80.0   17
1    tom   60.5   15

In [59]:
print(df.sort_values(by='score'))

    name  score  age
3  alice   30.6   20
1    tom   60.5   15
4    bob   70.0   26
2   jack   80.0   17
5  allen   83.5   30

In [ ]:
df = pd.DataFrame(
    {
        "name":["tom","tom",'jack','alice','bob','allen'],
        "age":[15,15,15,20,26,30],
        "score":[60.5,60.5,80,30.6,70,80]
    },index=[1,2,3,4,5,6],columns=["name","score","age"]
)

In [61]:
print(df.sort_values(by=['score','age'],ascending=[True,False]))

    name  score  age
3  alice   30.6   20
1    tom   60.5   15
4    bob   70.0   26
2   jack   80.0   17
5  allen   83.5   30

In [62]:
df.nlargest(2,columns=['score','age'])
df.nsmallest(2,columns=['score','age'])

    name  score  age
3  alice   30.6   20
1    tom   60.5   15

In [65]:
'''
案例1：学生成绩分析
场景：某班级的学生成绩数据如下，请完成以下任务：
1. 计算每位学生的总分和平均分。
2. 找出数学成绩高于90分或英语成绩高于85分的学生。
3. 按总分从高到低排序，并输出前3名学生。
'''
import pandas as pd
data = {
    '姓名': ['张三', '李四', '王五', '赵六', '钱七'],
    '数学': [85, 92, 78, 88, 95],
    '英语': [90, 88, 85, 92, 80],
    '物理': [75, 80, 88, 85, 90]
}
scores = pd.DataFrame(data)
scores['总分']=scores[['数学','英语','物理']].sum(axis=1)
scores['平均分']=scores['总分']/3
scores['平均分2'] = scores[['数学','英语','物理']].mean(axis=1)
#2. 找出数学成绩高于90分或英语成绩高于85分的学生。
result = scores[(scores['数学'] > 90) | (scores['英语'] > 85)]
print(result)
#3. 按总分从高到低排序，并输出前3名学生。
r1 = scores.sort_values('总分',ascending=False).head(3)
r2 =scores.nlargest(3,columns=['总分'])
print(r1)
print(r2)

   姓名  数学  英语  物理   总分        平均分       平均分2
0  张三  85  90  75  250  83.333333  83.333333
1  李四  92  88  80  260  86.666667  86.666667
3  赵六  88  92  85  265  88.333333  88.333333
4  钱七  95  80  90  265  88.333333  88.333333
   姓名  数学  英语  物理   总分        平均分       平均分2
3  赵六  88  92  85  265  88.333333  88.333333
4  钱七  95  80  90  265  88.333333  88.333333
1  李四  92  88  80  260  86.666667  86.666667
   姓名  数学  英语  物理   总分        平均分       平均分2
3  赵六  88  92  85  265  88.333333  88.333333
4  钱七  95  80  90  265  88.333333  88.333333
1  李四  92  88  80  260  86.666667  86.666667

In [66]:
'''
案例2：销售数据分析
场景：某公司销售数据如下，请完成以下任务：
1. 计算每种产品的总销售额（销售额 = 单价 × 销量）。
2. 找出销售额最高的产品。
3. 按销售额从高到低排序，并输出所有产品信息。
'''
import pandas as pd

data = {
    '产品名称': ['A', 'B', 'C', 'D'],
    '单价': [100, 150, 200, 120],
    '销量': [50, 30, 20, 40]
}
df = pd.DataFrame(data)
df['总销售额'] = df['单价']*df['销量']
df.nlargest(1,columns=['总销售额'])
df.sort_values('总销售额',ascending=False)

  产品名称   单价  销量  总销售额
0    A  100  50  5000
3    D  120  40  4800
1    B  150  30  4500
2    C  200  20  4000

In [67]:
'''案例3：电商用户行为分析
场景：某电商平台的用户行为数据如下，请完成以下任务：
1. 计算每位用户的总消费金额（消费金额 = 商品单价 × 购买数量）
2. 找出消费金额最高的用户，并输出其所有信息
3. 计算所有用户的平均消费金额（保留2位小数）
4. 统计电子产品的总购买数量
'''
import pandas as pd

data = {
    '用户ID': [101, 102, 103, 104, 105],
    '用户名': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    '商品类别': ['电子产品', '服饰', '电子产品', '家居', '服饰'],
    '商品单价': [1200, 300, 800, 150, 200],
    '购买数量': [1, 3, 2, 5, 4]
}
df = pd.DataFrame(data)
df['总消费金额'] = df['商品单价']*df['购买数量']
df.nlargest(1,columns=['总消费金额'])
df['总消费金额'].mean()
df[df['商品类别']=='电子产品']['购买数量'].sum()

np.int64(3)